Repository aquarist-labs/s3gw-tools, pull requests merged in 2022-04, with the labels that each got.

#10 s3gw: expand README
  README.md
  assets/images/s3gw-roadmap.jpg
Labels: enhancement

#14 readme: update a few things related to running radosgw
  README.md
Labels: enhancement

#11 Containerize RGW with minimal dependencies
  .editorconfig
  .gitignore
  .s3cfg
  README.md
  build/Dockerfile.build-radosgw
  build/README.md
  build/build-container.sh
  build/build-radosgw.sh
Labels: feature

#21 Disable some more flags
  build/build-radosgw.sh
Labels: enhancement

#23 k3s: Run k3s in rootless mode.
  k3s/.gitignore
  k3s/longhorn-pvc.yaml
  k3s/longhorn-storageclass.yaml
  k3s/s3gw-ingress.yaml
  k3s/s3gw-pod.yaml
  k3s/s3gw-service.yaml
  k3s/setup.sh
Labels: enhancement, feature

#24 k3s: Make sure open-iscsi is installed
  k3s/setup.sh
Labels: enhancement

#25 k3s: Use prefix to access S3 API and Longhorn UI
  k3s/README.md
  k3s/longhorn-ingress.yaml
  k3s/s3cmd.cfg
  k3s/s3gw-ingress.yaml
  k3s/s3gw-namespace.yaml
  k3s/s3gw-pod.yaml
  k3s/s3gw-pvc.yaml
  k3s/s3gw-service.yaml
  k3s/setup.sh
Labels: enhancement
