Repository aquarist-labs/s3gw-tools, pull requests merged in 2022-11, with the labels that each got.

#189 Unify hostnames for TLS/non-TLS traffic.
  env/ingress-traefik/s3gw-ingress.yaml
  env/ingress-traefik/s3gw-ui-ingress.yaml
  env/s3gw-dev.yaml
  env/s3gw.yaml
  env/setup.sh
Labels: kind/enhancement

#190 Update changelog for v0.8.0.
  CHANGELOG.md
Labels: kind/documentation

#192 tools: add new rgw/sfs unit tests
  CHANGELOG.md
  build/Dockerfile.build-radosgw-test-container
  build/build-radosgw.sh
  build/build.sh
Labels: component/tests

#193 tools: Fix test container Dockerfile
  build/Dockerfile.build-radosgw-test-container
Labels: kind/bug
