Repository aquarist-labs/s3gw-tools, pull requests merged in 2022-09, with the labels that each got.

#169 Adds PR template to Tools repository
  .github/pull_request_template.md
Labels: feature

#171 Update tests/s3gw-buckets-rest-api-test.py
  tests/s3gw-buckets-rest-api-test.py
Labels: bug

#170 test/smoke: versioning tests with delete markers
  tests/s3gw-versioning-smoke-tests.py
Labels: enhancement, feature

#166 env/setup.sh: longhorn custom settings
  CHANGELOG.md
  env/.gitignore
  env/longhorn-setting.yaml.sample
  env/setup.sh
Labels: enhancement

#175 build/s3gw-test: s3gw-test image
  CHANGELOG.md
  build/Dockerfile.build-radosgw-test-container
  build/build-radosgw-test-container.sh
  build/build-radosgw.sh
  build/build.sh
Labels: enhancement
