Repository aquarist-labs/s3gw-tools, pull requests merged in 2022-08, with the labels that each got.

#122 Improve UI Dockerfile.
  build-ui/Dockerfile.app
  build-ui/Dockerfile.app-builder
  build-ui/Dockerfile.s3gw-ui
  build-ui/build-app.sh
  build-ui/build-ui.sh
  build-ui/build.sh
  docs/build-ui.md
  env/generate-spec.sh
  env/s3gw-dev.yaml
  env/s3gw.yaml
  env/s3gw/s3gw-config.yaml
  env/setup.sh
Labels: enhancement

#138 Improve build/setup scripts
  build-ui/build.sh
  env/setup.sh
Labels: enhancement

#137 Various improvements
  README.md
  build/build-radosgw.sh
  docs/build-ui.md
  docs/build.md
  docs/contributing.md
  docs/decisions/0000-use-markdown-any-decision-records.md
  docs/decisions/README.md
  docs/env-k3s.md
  docs/release-notes/s3gw-v0.1.0.md
  docs/s3gw-repos.md
  env/setup.sh
Labels: enhancement

#141 Add '--no-s3gw' argument to install k3s (and iSCSI + Longhorn) only.
  env/setup.sh
Labels: enhancement

#142 Remove docs and add changelog.
  CHANGELOG.md
  docs/build-ui.md
  docs/build.md
  docs/contributing.md
  docs/decisions/.markdownlint.yml
  docs/decisions/0000-use-markdown-any-decision-records.md
  docs/decisions/README.md
  docs/decisions/adr-template.md
  docs/developing.md
  docs/env-k3s.md
  docs/env-k8s.md
  docs/release-notes/s3gw-v0.1.0.md
  docs/s3-compatibility-table.md
  docs/s3gw-repos.md
  docs/testing.md
Labels: cleanup

#143 Display a hint how to workaround the HTTPS/CORS issue.
  env/setup.sh
Labels: enhancement

#144 Call correct function.
  env/setup.sh
Labels: bug

#145 If '--dev' is enabled, the s3gw-ui image is not imported.
  env/setup.sh
Labels: bug

#146 Adapt the access/secret key in s3cmd.cfg to the values that are deployed by the scripts.
  env/s3cmd.cfg
Labels: bug, cleanup

#147 Display all existing URLs.
  env/setup.sh
Labels: cleanup

#149 Fix setup script (call correct function).
  env/setup.sh
Labels: bug

#150 Display more information.
  env/setup.sh
Labels: enhancement

#153 tests: Add unit test for the '/admin/metadata/user' AdminOps API endpoint.
  tests/s3gw-users-rest-api-test.py
Labels: enhancement

#155 Adapt name of sample/template file.
  build-ui/Dockerfile.app
Labels: bug

#87 tests: add helper to run scripts
  tests/s3gw-test.sh
Labels: enhancement

#154 Set 'system' flag for default user
  env/s3gw-dev.yaml
  env/s3gw.yaml
  env/s3gw/s3gw-config.yaml
Labels: enhancement

#159 Ignore __pycache__ directories.
  .gitignore
Labels: enhancement

#160 Add values for default user.
  env/s3gw/s3gw-config.yaml
Labels: enhancement
